version: "3.5"

services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=avaxnodes.com"
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  avaxnodes:
    container_name: avaxnodes
    build:
      # context: ./sites/avaxnodes.com
      context: .
      dockerfile: Dockerfile
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=avaxnodes"
      - "traefik.frontend.rule=Host:avaxnodes.com"
    ports:
      - "7600:3000"
