const routes = require('next-routes')

module.exports = routes()
  .add('en-home', '/:locale(en)?', 'home')
  .add('ja-home', '/:locale(ja)', 'home')
  .add('ko-home', '/:locale(ko)', 'home')
  .add('nl-home', '/:locale(nl)', 'home')
  .add('zh-home', '/:locale(zh)', 'home')
  .add('en-node', '/:locale(en)?/node/:id', 'node')
  .add('ja-node', '/:locale(ja)/node/:id', 'node')
  .add('ko-node', '/:locale(ko)/node/:id', 'node')
  .add('nl-node', '/:locale(nl)/knooppunt/:id', 'node')
  .add('zh-node', '/:locale(zh)/node/:id', 'node')
  .add('en-404', '/:locale(en)?/404', '404')
  .add('ja-404', '/:locale(ja)/404', '404')
  .add('ko-404', '/:locale(ko)/404', '404')
  .add('nl-404', '/:locale(nl)/404', '404')
  .add('zh-404', '/:locale(zh)/404', '404')
