const routes = require('next-routes')

module.exports = routes()
  .add('en-home', '/:locale(en)?', 'home')
  .add('ja-home', '/:locale(ja)', 'home')
  .add('ko-home', '/:locale(ko)', 'home')
  .add('nl-home', '/:locale(nl)', 'home')
  .add('zh-home', '/:locale(zh)', 'home')

  .add('en-node', '/:locale(en)?/node/:id', 'node')
  .add('ja-node', '/:locale(ja)/node/:id', 'node')
  .add('ko-node', '/:locale(ko)/node/:id', 'node')
  .add('nl-node', '/:locale(nl)/knooppunt/:id', 'node')
  .add('zh-node', '/:locale(zh)/node/:id', 'node')

  .add('en-404', '/:locale(en)?/404', '404')
  .add('ja-404', '/:locale(ja)/404', '404')
  .add('ko-404', '/:locale(ko)/404', '404')
  .add('nl-404', '/:locale(nl)/404', '404')
  .add('zh-404', '/:locale(zh)/404', '404')

  .add('en-providers', '/:locale(en)?/providers', 'providers')
  .add('ja-providers', '/:locale(ja)/providers', 'providers')
  .add('ko-providers', '/:locale(ko)/providers', 'providers')
  .add('nl-providers', '/:locale(nl)/providers', 'providers')
  .add('zh-providers', '/:locale(zh)/providers', 'providers')

  .add('en-delegations', '/:locale(en)?/delegations', 'delegations')
  .add('ja-delegations', '/:locale(ja)/delegations', 'delegations')
  .add('ko-delegations', '/:locale(ko)/delegations', 'delegations')
  .add('nl-delegations', '/:locale(nl)/delegations', 'delegations')
  .add('zh-delegations', '/:locale(zh)/delegations', 'delegations')

  .add('en-x-chain', '/:locale(en)?/x-chain', 'x-chain')
  .add('ja-x-chain', '/:locale(ja)/x-chain', 'x-chain')
  .add('ko-x-chain', '/:locale(ko)/x-chain', 'x-chain')
  .add('nl-x-chain', '/:locale(nl)/x-chain', 'x-chain')
  .add('zh-x-chain', '/:locale(zh)/x-chain', 'x-chain')

  .add('en-c-chain', '/:locale(en)?/c-chain', 'c-chain')
  .add('ja-c-chain', '/:locale(ja)/c-chain', 'c-chain')
  .add('ko-c-chain', '/:locale(ko)/c-chain', 'c-chain')
  .add('nl-c-chain', '/:locale(nl)/c-chain', 'c-chain')
  .add('zh-c-chain', '/:locale(zh)/c-chain', 'c-chain')

  .add('en-notifier', '/:locale(en)?/notifier', 'notifier')
  .add('ja-notifier', '/:locale(ja)/notifier', 'notifier')
  .add('ko-notifier', '/:locale(ko)/notifier', 'notifier')
  .add('nl-notifier', '/:locale(nl)/notifier', 'notifier')
  .add('zh-notifier', '/:locale(zh)/notifier', 'notifier')
